$templatePath = './azurePolicyDefinitionSet.parameters.json'
$initiativeName = "Managed Infra - Tagging Policy"
$initiativeDescription = "Managed Infra - Generated by InSpark Pipeline"
$initiativeCategory = "tagging"


$policy = Get-AzPolicyDefinition -ManagementGroupName "CIA" -Custom | Where-Object {$_.properties.description -eq "Managed Infra - Generated by InSpark Pipeline"}| select-Object PolicyDefinitionId| ConvertTo-Json
$policy = $policy | ConvertFrom-Json -AsHashtable

$armTemplate = Get-Content -Path $templatePath -Raw | ConvertFrom-Json -AsHashtable
$armTemplate.parameters.policyDefinitionId.value = $policy
$armTemplate.parameters.defaultPolicyDefinitions.value = @()
$armTemplate.parameters.displayName.value = $initiativeName
$armTemplate.parameters.initiativeName.value = $initiativeName
$armTemplate.parameters.description.value = $initiativeDescription
$armTemplate.parameters.metadata.value.category = $initiativeCategory


$armTemplate | ConvertTo-Json -Depth 10 | Out-File ./azurePolicyDefinitionSet2.parameters.json